[package]
name = "hushpaperwallet"
version = "0.1.2"
authors = [
	"ZecWallet",
    "The Hush developers"
]
edition = "2018"
    
[dependencies]
clap = "2.33.0"
hushpaperlib = { path = "../lib" }
json = "0.11.14"
printpdf = "0.3.2"